# Generated by Django 3.2.12 on 2022-04-25 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Когда зарегистрировался')),
                ('code', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Код подтверждения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customer.user')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('delivery_info', models.TextField(blank=True, null=True, verbose_name='Доставка')),
                ('spent_money', models.IntegerField(default=0, verbose_name='Потрачено денег')),
                ('last_buy', models.DateField(blank=True, null=True, verbose_name='Последний раз купил')),
                ('subscribed', models.BooleanField(default=True, verbose_name='Подписка на рассылку')),
            ],
            managers=[
                ('subscribed_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
