# Generated by Django 3.2.12 on 2022-04-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stuff',
        ),
    ]
