# Generated by Django 3.2.12 on 2022-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220410_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_buy',
            field=models.DateField(blank=True, null=True, verbose_name='Последний раз купил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
