# Generated by Django 3.2.12 on 2022-04-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20220414_1645'),
        ('customer', '0007_auto_20220414_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
