# Generated by Django 3.2.12 on 2022-04-14 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0002_alter_coupon_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст рекламной рассылки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('confirm', models.BooleanField(default=True, verbose_name='Согласие на получение')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
