# Generated by Django 3.2.12 on 2022-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Желтый', 'Желтый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Черный', 'Черный'), ('Золотой', 'Золотой')], max_length=250, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.Likes'),
        ),
    ]
